apiVersion: v1
kind: ConfigMap
metadata:
  name: event-config
  namespace: college-events
data:
  MYSQL_DATABASE: college_events
  MYSQL_USER: eventuser
  DB_HOST: mysql
  DB_PORT: "3306"
  DB_NAME: college_events
  DB_USER: eventuser
  CORS_ORIGIN: "*"
---
apiVersion: v1
kind: Secret
metadata:
  name: event-secrets
  namespace: college-events
type: Opaque
stringData:
  MYSQL_PASSWORD: eventpass123
  MYSQL_ROOT_PASSWORD: rootpass123
  JWT_SECRET: change-this-to-a-long-random-secret
